[package]
name = "networkingp"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "main2"
path = "src/bin/tcp-client.rs"

[dependencies]
