name: Rust Test and Launch

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache rust installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: set-up
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

  test:
    runs-on: ubuntu-latest
    needs: set-up
    steps:
      - uses: actions/checkout@v5
      - name: Cache rust installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      # Lint formatting
      # - name: Check formatting
      #  run: cargo fmt --all -- --check

      # Lint with Clippy
      #- name: Run clippy
      #  run: cargo clippy --all-targets -- -D warnings

      - name: testing
        run: |
          cargo check
          cargo test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - name: Cache rust installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build
        run: cargo build --release
